Repository HumanAppEfrei/Sentin-Ailes, pull requests merged in 2020-04, with the labels that each got.

#3 Feature/events list
  package.json
  src/components/EmergencyContact.vue
  src/components/EventCard.vue
  src/router/index.js
  src/views/EventsList.vue
  yarn.lock
Labels: enhancement

#5 Feature/event request vue
  src/components/EventRequestCard.vue
  src/router/index.js
  src/views/CalendarHub.vue
  src/views/EventRequest.vue
Labels: enhancement

#8 Feature/calcul mental
  src/router/index.js
  src/views/CalculGame.vue
  src/views/ExercisesHub.vue
Labels: enhancement

#15 Re-enable eslint rules that were causing build to fail
  .eslintrc.js
  .gitignore
Labels: bug

#17 Fix note border
  src/components/NoteCard.vue
Labels: design

#18 Feature/fix tile icons not centered
  src/components/MenuTile.vue
Labels: design
